from . import start
from .tarif import dp
from .ivents import dp
from .profile import dp
from .networking import dp
from .ads import dp
from .faq import dp
from .help import dp
from .myIvents import dp
from .actual import dp