# Generated by Django 4.0.2 on 2022-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IventStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.TextField(verbose_name='place_id')),
                ('place', models.TextField(verbose_name='place')),
                ('visit_now', models.TextField(verbose_name='visit_now')),
                ('visit_future', models.TextField(verbose_name='visit_future')),
            ],
            options={
                'verbose_name': 'Ivent statistics',
                'verbose_name_plural': 'Ivent statistic',
                'db_table': 'ivent_statistic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField(verbose_name='tg_id')),
                ('name', models.TextField(null=True, verbose_name='name')),
                ('phone', models.TextField(null=True, verbose_name='phone')),
                ('visit_now', models.TextField(verbose_name='visit_now')),
                ('visit_future', models.TextField(verbose_name='visit_future')),
            ],
            options={
                'verbose_name': 'User statistics',
                'verbose_name_plural': 'User statistic',
                'db_table': 'user_stat',
                'managed': True,
            },
        ),
    ]
