# Generated by Django 4.0.4 on 2022-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iventstatistic',
            name='place',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='iventstatistic',
            name='visit_future',
            field=models.TextField(verbose_name='Собираются посетить'),
        ),
        migrations.AlterField(
            model_name='iventstatistic',
            name='visit_now',
            field=models.TextField(verbose_name='Уже посетили'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='phone',
            field=models.TextField(null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='tg_id',
            field=models.TextField(verbose_name='Телеграм id'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='visit_future',
            field=models.TextField(verbose_name='Собирается посетить'),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='visit_now',
            field=models.TextField(verbose_name='Уже посетил'),
        ),
    ]
