# Generated by Django 4.0.2 on 2022-02-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('desc', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'kategory',
                'verbose_name_plural': 'kategory',
                'db_table': 'kategory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField(verbose_name='tg_id')),
                ('photo', models.TextField(null=True, verbose_name='photo')),
                ('name', models.TextField(null=True, verbose_name='name')),
                ('phone', models.TextField(null=True, verbose_name='phone')),
                ('status', models.TextField(verbose_name='status')),
                ('tarif', models.TextField(null=True, verbose_name='tarif')),
                ('dead_line', models.TextField(null=True, verbose_name='dead_line')),
                ('length', models.TextField(null=True, verbose_name='lenght')),
                ('weight', models.TextField(null=True, verbose_name='weight')),
                ('age', models.TextField(null=True, verbose_name='age')),
                ('field_activity', models.TextField(null=True, verbose_name='ocupation')),
            ],
            options={
                'verbose_name': 'Who with',
                'verbose_name_plural': 'Who with',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
            ],
            options={
                'verbose_name': 'Who with',
                'verbose_name_plural': 'Who with',
                'db_table': 'who',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlacesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.kategory')),
            ],
            options={
                'verbose_name': 'places group',
                'verbose_name_plural': 'places group',
                'db_table': 'plases_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('desc', models.TextField(verbose_name='description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.placesgroup')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'places',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='kategory',
            name='for_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.who'),
        ),
    ]
