# Generated by Django 4.0.2 on 2022-02-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'users', 'verbose_name_plural': 'user'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='length',
            new_name='lenght',
        ),
    ]
