# Generated by Django 4.0.2 on 2022-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_rename_field_activity_user_ocupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategory',
            name='for_who',
        ),
        migrations.AddField(
            model_name='kategory',
            name='for_who',
            field=models.ManyToManyField(to='panel.Who'),
        ),
    ]
