# Generated by Django 4.0.2 on 2022-02-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_kategory_for_who_kategory_for_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategory',
            name='for_who',
        ),
        migrations.AddField(
            model_name='kategory',
            name='for_who',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='panel.who'),
            preserve_default=False,
        ),
    ]
