# Generated by Django 4.0.2 on 2022-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_ads_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.TextField(verbose_name='tg_id')),
            ],
            options={
                'verbose_name': 'Admins',
                'verbose_name_plural': 'Admin',
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='ads_db',
            options={'managed': True, 'verbose_name': 'ADS', 'verbose_name_plural': 'ADS'},
        ),
    ]
