# Generated by Django 4.0.4 on 2022-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_admin_alter_ads_db_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название места/мероприятия')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'active place',
                'verbose_name_plural': 'active places',
                'db_table': 'act_places',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='kategory',
            options={'managed': True, 'verbose_name': 'kategory', 'verbose_name_plural': 'kategorys'},
        ),
        migrations.AlterModelOptions(
            name='who',
            options={'managed': True, 'verbose_name': 'who', 'verbose_name_plural': 'who'},
        ),
        migrations.AlterField(
            model_name='ads_db',
            name='address',
            field=models.TextField(verbose_name='Адрес места'),
        ),
        migrations.AlterField(
            model_name='ads_db',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ads_db',
            name='link',
            field=models.TextField(verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='ads_db',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ads_db',
            name='phone',
            field=models.TextField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='kategory',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='kategory',
            name='name',
            field=models.TextField(verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(verbose_name='Название места/мероприятия'),
        ),
        migrations.AlterField(
            model_name='placesgroup',
            name='name',
            field=models.TextField(verbose_name='Название группы мест'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.TextField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dead_line',
            field=models.TextField(null=True, verbose_name='Дата окончания тарифа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lenght',
            field=models.TextField(null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.TextField(null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(null=True, verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.TextField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarif',
            field=models.TextField(null=True, verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.TextField(null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='who',
            name='name',
            field=models.TextField(verbose_name='Название группы'),
        ),
    ]
