# Generated by Django 3.2.8 on 2022-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_actplace_alter_kategory_options_alter_who_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'db_table': 'chat',
                'managed': True,
            },
        ),
    ]
